### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by TommyLemon** [tianzhijiexian/DBinding#8]
Gradle 'DBinding-master' project refresh failed
Error:Cause: com/android/build/gradle/internal/model/DefaultAndroidProject : Unsupported major.minor version 52.0

项目jdk版本有1.7，1.8两种，试过了compile jdk统一为1.7，1.8 ,clean，build等都不行

**Comment by kaleai** [comment]
这个库里面没有引入这个东西呢，你可以清空目录，然后重新拉下代码看一下。

**Comment by TommyLemon** [comment]
@tianzhijiexian 是因为没装插件吗？我尝试用Android Studio intall plugin from disk安装插件，DbindPlugin.jar能装，pluginLib不能装。重启studio后报错：
Plugin Error：
Dbinding Plugin threw an uncaught PluginException.

DbindPlugin对解压路径有要求吗？

**Comment by TommyLemon** [comment]
Plugin Error具体是：
cannot create class "kale.dbinding.plugin.ViewModelGenerator" [Plugin: kale.dbinding.plugin]
com.intellij.diagnostic.PluginException: cannot create class "kale.dbinding.plugin.ViewModelGenerator" [Plugin: kale.dbinding.plugin]
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:177)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convert(ActionManagerImpl.java:515)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getActionImpl(ActionManagerImpl.java:495)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.java:488)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.unStub(DefaultActionGroup.java:354)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.getChildren(DefaultActionGroup.java:312)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$5.compute(ActionManagerImpl.java:1315)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$5.compute(ActionManagerImpl.java:1308)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:967)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.preloadActionGroup(ActionManagerImpl.java:1308)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.preloadActionGroup(ActionManagerImpl.java:1302)
	at com.intellij.codeInsight.generation.actions.GenerateAction.preload(GenerateAction.java:99)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.preloadActionGroup(ActionManagerImpl.java:1320)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.preloadActionGroup(ActionManagerImpl.java:1323)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.preloadActionGroup(ActionManagerImpl.java:1302)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.doPreloadActions(ActionManagerImpl.java:1290)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.access$200(ActionManagerImpl.java:77)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$4.run(ActionManagerImpl.java:1278)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:366)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)
Caused by: com.intellij.diagnostic.PluginException: kale/dbinding/plugin/ViewModelGenerator : Unsupported major.minor version 52.0 [Plugin: kale.dbinding.plugin]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:130)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:77)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:66)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:249)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:153)
	... 25 more
Caused by: java.lang.UnsupportedClassVersionError: kale/dbinding/plugin/ViewModelGenerator : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:471)
	at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:260)
	at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:256)
	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:225)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:124)
	... 31 more

**Comment by TommyLemon** [comment]
具体环境及配置是
mac osx ei capitan
jdk 1.8.0_91（改成1.7.0_71还是一样错误）
android studio 2.1.2
android plugin version 2.2.3(好像是Android Studio默认配置)
gradle 2.14.1：use default gradle wrapper(工程默认配置)

**Comment by TommyLemon** [comment]
@tianzhijiexian Win7+AndroidStudio2.2+use embedded JDK(recommanded),其它配置和以上一样，运行成功。
希望作者做下环境配置的兼容性测试，提供建议配置及常见问题的解决教程

**Comment by kaleai** [comment]
感谢提醒，我检测下mirror这个东西，删掉就好。我处理一下
